---
- hosts: localhost
  connection: local
  become: true
  vars:
    username: bob
    git_repo: "https://github.com/anaxios/ansible.git"

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - import_tasks: tasks/users.yml
    - import_tasks: tasks/sshd.yml
    - import_tasks: tasks/aliases.yml
#    - import_tasks: tasks/bashrc.yml
    - import_tasks: tasks/packages.yml

