- name: install SSH public keys
  ansible.posix.authorized_key:
    user: {{ username }} 
    state: present
    key: "{{ lookup('file', './files/id_ed25519.pub') }}"

- name: set password auth to no in /etc/ssh/sshd_config
  lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: '^#?PasswordAuthentication'
      line: 'PasswordAuthentication no'
  register: file

- name: set pubkey auth to yes in /etc/ssh/sshd_config
  lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: '^#?PubkeyAuthentication'
      line: 'PubkeyAuthentication yes'
  register: file

- name: set authroized keys file in /etc/ssh/sshd_config
  lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: '^#?AuthorizedKeysFile'
      line: 'AuthorizedKeysFile .ssh/authorized_keys .ssh/authorized_keys2'
  register: file

  #- name: restart sshd service
  #  service:
  #          name: sshd
  #          state: restarted
  #          enabled: yes
  #  when: file.changed

          #          - name: Wait for the reboot and reconnect 
          #            wait_for:
          #                     port: 22
          #                     host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
          #                     search_regex: OpenSSH
          #                     delay: 10
          #                     timeout: 60
          #            connection: local
