#- name: add ansible user
#  user:
#    name: ansible
#    system: yes

# - name: set up sudo for user ansible
#   blockinfile:
#     path: /etc/sudoers.d/ansible
#     create: yes
#     backup: true
#     state: present
#     owner: root
#     group: root
#     mode: 0440
#     block: |
#       ansible ALL=(ALL) NOPASSWD: ALL

#- name: add ansible-pull cron job
#  cron:
#    name: ansible auto-provision
#    user: ansible
#    minute: "*/10"
#    job: ansible-pull -o -U {{ git_repo }} 

- name: add user bob
  ansible.builtin.user:
    name: "{{ username }}"
    system: no 
    shell: /usr/bin/bash
    #groups: "sudo"
    #password: "{{ 'password' | password_hash('sha512') }}"
    #update_password: on_create
    # register: pas

    #- name: for user to change password
    #  shell: change -d 0 {{ username }}
    #  when: pas.changed
    #

- name: set up sudo for user
  blockinfile:
    path: /etc/sudoers.d/{{ username }}
    create: yes
    backup: true
    state: present
    owner: root
    group: root
    mode: 0440
    block: |
      {{ username }} ALL=(ALL) NOPASSWD: ALL
