#- name: add ansible user
#  user:
#    name: ansible
#    system: yes

#- name: set up sudo for ansible user
#  copy:
#    src: files/sudoer_ansible
#    dest: /etc/sudoers.d/ansible
#    owner: root
#    group: root
#    mode: 0440

    #- name: add ansible-pull cron job
    #  cron:
    #    name: ansible auto-provision
    #    user: ansible
    #    minute: "*/10"
    #    job: ansible-pull -o -U {{ git_repo }} 

- name: add user bob
  user:
    name: "{{ username }}"
    system: no 

- name: set up sudo for user
  copy:
    src: files/sudoer_{{ username }}
    dest: /etc/sudoers.d/{{ username }}
    owner: root
    group: root
    mode: 0440
